language: python
python: "2.7"

install:
  - pip install ansible

script:
  - ansible-playbook -i inventory_exercise install-docker.yml
  - ansible-playbook -i inventory_exercise deploy_static_webpage.yml


