---
- name: Install Docker
  hosts: exercise 
  become: True
  
  tasks:
  - name: Install Docker | install packages
    yum: name={{item}} state=present
    with_items: 
    - docker
    - docker-common
    - container-selinux

  - name: Install Docker | enable docker
    service: name=docker enabled=yes state=started
